# -
# Colors for embeds
# Deleting these lines will make the default embeds use the colors originally defined here
# -

default_color = 0x30b521
system_color = 0x8C8B8B
red_color = 0xff0000
yellow_color = 0xeaff00
blue_color = 0x0066ff



# -
# Default embed settings
# You can delete those lines or set their value to nothing and to False, accordingly to not have a default thumbnail and not display the time on embeds' footers by default
# -

default_embed_thumbnail = https://media.discordapp.net/attachments/1178067146908123267/1178373863843823746/HC.png?ex=65b682ae&is=65a40dae&hm=ad9b8f9a149e201c4302720cf864084dccabdb54214f6ff98a5cae42c7c30721&=&format=webp&quality=lossless&width=603&height=603
default_embed_displaytime = True

